dellstore2=# CREATE RULE orders_2004_q1_insert AS                                                                                                                                                           ON INSERT TO orders                                                                                                                                                                                         WHERE (  orderdate >= DATE '2004-01-01'                                                                                                                                                                     AND   orderdate < DATE '2004-04-01' )                                                                                                                                                                       DO INSTEAD                                                                                                                                                                                                      INSERT INTO orders_2004_q1 VALUES (NEW.*);
CREATE RULE
dellstore2=# CREATE RULE orders_2004_q2_insert AS                                                                                                                                                           ON INSERT TO orders                                                                                                                                                                                         WHERE (  orderdate >= DATE '2004-04-01'                                                                                                                                                                     AND   orderdate < DATE '2004-07-01' )                                                                                                                                                                       DO INSTEAD                                                                                                                                                                                                      INSERT INTO orders_2004_q2 VALUES (NEW.*);
CREATE RULE
dellstore2=# CREATE RULE orders_2004_q3_insert AS                                                                                                                                                           ON INSERT TO orders                                                                                                                                                                                         WHERE (  orderdate >= DATE '2004-07-01'                                                                                                                                                                     AND   orderdate < DATE '2004-10-01' )                                                                                                                                                                       DO INSTEAD                                                                                                                                                                                                      INSERT INTO orders_2004_q3 VALUES (NEW.*);
CREATE RULE
dellstore2=# CREATE RULE orders_2004_q4_insert AS                                                                                                                                                           ON INSERT TO orders                                                                                                                                                                                         WHERE (  orderdate >= DATE '2004-10-01'                                                                                                                                                                     AND   orderdate < DATE '2005-01-01' )                                                                                                                                                                       DO INSTEAD                                                                                                                                                                                                      INSERT INTO orders_2004_q4 VALUES (NEW.*);
CREATE RULE

